export const FETCH_BASKETPRODUCTS_REQUEST = "FETCH_BASKETPRODUCTS_REQUEST";
export const FETCH_BASKETPRODUCTS_SUCCESS = "FETCH_BASKETPRODUCTS_SUCCESS";
export const FETCH_BASKETPRODUCTS_FAILURE = "FETCH_BASKETPRODUCTS_FAILURE";
